name: Lint and Tests
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  do-lint:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        run: npm ci
      - id: do-lint
        name: Lint
        run: npm run lint
  do-test:
    runs-on: ubuntu-latest
    needs: do-lint
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        run: npm ci
      - id: do-test
        name: Test
        run: npm run test

